# 빅데이터 분석기사 실기 주의점
- 자동완성 X (help()함수 사용가능)
- 코드 실행시간 1분으로 제한( 복잡한 코드 실행 불가 )
- numpy, pnadas, scikit-learn, scipy, xgboost
- beautifulsoup4, selenium

In [4]:
import numpy as np
test = np.array([1,2,3,4], float)
test

array([1., 2., 3., 4.])

# 다차원 배열
- ndarray의 모든 원소는 같은 자료형만 사용가능
- 배열의 차원을 rank라고 함
- 차원의 크기를 튜플로 표시하는 것을 shape
- 1차원 배열 = vector / 2차원 배열 = matrix / 3차원 배열 = tensor
# 예제 ( 행 2 / 열 3) 배열
- rank = 2 (2차원 배열)
- shape = (2, 3)


In [14]:
# 절대값 abs, fabs 
test_a = [ -1.2345, 2.3456, -3.4567, 4,5689 ]
test_b = [ 1.2, -2.3, 3.4, -4.5 ]
test_a_arr = np.array(test_a)
test_b_arr = np.array(test_b)

print(" 결과물 ")
print(f'testa{test_a_arr}')
print(f'testb{test_b_arr}')

print(" abs ")
print(np.abs(test_a_arr))
print(np.abs(test_b_arr))

print(" fabs ") # 복소수가 아닌 경우 빠른 연산을 위해 abs가아닌 fabs 사용
print(np.fabs(test_a_arr))
print(np.fabs(test_b_arr))

 결과물 
testa[-1.2345e+00  2.3456e+00 -3.4567e+00  4.0000e+00  5.6890e+03]
testb[ 1.2 -2.3  3.4 -4.5]
 abs 
[1.2345e+00 2.3456e+00 3.4567e+00 4.0000e+00 5.6890e+03]
[1.2 2.3 3.4 4.5]
 fabs 
[1.2345e+00 2.3456e+00 3.4567e+00 4.0000e+00 5.6890e+03]
[1.2 2.3 3.4 4.5]


In [20]:
# 제곱근 sqrt
test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
#print(np.sqrt(test_a))
for index,value in enumerate(np.sqrt(test_a)):
    print( index+1, value )


1 1.0
2 1.4142135623730951
3 1.7320508075688772
4 2.0
5 2.23606797749979
6 2.449489742783178
7 2.6457513110645907
8 2.8284271247461903
9 3.0
10 3.1622776601683795
11 3.3166247903554
12 3.4641016151377544
13 3.605551275463989
14 3.7416573867739413
15 3.872983346207417
16 4.0


In [21]:
# 제곱 square
test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

for index,value in enumerate(np.square(test_a)):
    print( index+1, value )


1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100
11 121
12 144
13 169
14 196
15 225
16 256


In [22]:
# 지수 exp 
# 4의 3제곱에서 4는 밑 3은 지수
# 7의 5제곱에서 7은 및 5는 지수

test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

for index,value in enumerate(np.exp(test_a)):
    print( index+1, value )





1 2.718281828459045
2 7.38905609893065
3 20.085536923187668
4 54.598150033144236
5 148.4131591025766
6 403.4287934927351
7 1096.6331584284585
8 2980.9579870417283
9 8103.083927575384
10 22026.465794806718
11 59874.14171519782
12 162754.79141900392
13 442413.3920089205
14 1202604.2841647768
15 3269017.3724721107
16 8886110.520507872


In [24]:
# 로그 log

test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

for index,value in enumerate(np.log(test_a)):
    print( index+1, value )





1 0.0
2 0.6931471805599453
3 1.0986122886681098
4 1.3862943611198906
5 1.6094379124341003
6 1.791759469228055
7 1.9459101490553132
8 2.0794415416798357
9 2.1972245773362196
10 2.302585092994046
11 2.3978952727983707
12 2.4849066497880004
13 2.5649493574615367
14 2.6390573296152584
15 2.70805020110221
16 2.772588722239781


In [25]:
# 배열의 덧셈 add

test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
test_b = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

for index,value in enumerate(np.add(test_a, test_b)):
    print( index+1, value )





1 2
2 4
3 6
4 8
5 10
6 12
7 14
8 16
9 18
10 20
11 22
12 24
13 26
14 28
15 30
16 32


In [26]:
# 배열의 차 subtract

test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
test_b = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

for index,value in enumerate(np.subtract(test_a, test_b)):
    print( index+1, value )





1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0


In [27]:
# 배열의 곱 multiply

test_a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
test_b = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

for index,value in enumerate(np.multiply(test_a, test_b)):
    print( index+1, value )





1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100
11 121
12 144
13 169
14 196
15 225
16 256
